// <auto-generated />
using System;
using HoE.Plugins.EFCoreSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoE.Plugins.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(HoEContext))]
    partial class HoEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoE.CoreBusiness.Kalendar", b =>
                {
                    b.Property<int>("K_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("K_ID"));

                    b.Property<DateTime>("Date_Time")
                        .HasColumnType("datetime2");

                    b.HasKey("K_ID");

                    b.ToTable("Kalendars");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Level", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("T_ID"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Klass")
                        .HasColumnType("int");

                    b.Property<string>("Levels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("T_ID");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Student", b =>
                {
                    b.Property<int>("S_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_ID"));

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("S_ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HoE.CoreBusiness.SummaryTable", b =>
                {
                    b.Property<int>("T_ID")
                        .HasColumnType("int");

                    b.Property<int>("L_ID")
                        .HasColumnType("int");

                    b.Property<int>("S_ID")
                        .HasColumnType("int");

                    b.Property<int>("K_ID")
                        .HasColumnType("int");

                    b.Property<int?>("TLevelsT_ID")
                        .HasColumnType("int");

                    b.HasKey("T_ID", "L_ID", "S_ID", "K_ID");

                    b.HasIndex("K_ID");

                    b.HasIndex("L_ID");

                    b.HasIndex("S_ID");

                    b.HasIndex("TLevelsT_ID");

                    b.ToTable("SummaryTables");
                });

            modelBuilder.Entity("HoE.CoreBusiness.TAvaliable", b =>
                {
                    b.Property<int>("T_ID")
                        .HasColumnType("int");

                    b.Property<int>("K_ID")
                        .HasColumnType("int");

                    b.HasKey("T_ID", "K_ID");

                    b.HasIndex("K_ID");

                    b.ToTable("TAvaliables");
                });

            modelBuilder.Entity("HoE.CoreBusiness.TLevels", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("T_ID"));

                    b.Property<int>("L_ID")
                        .HasColumnType("int");

                    b.HasKey("T_ID");

                    b.ToTable("TLevels");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Teacher", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("T_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("T_ID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            T_ID = 1,
                            Name = "Katarzyna Sikora",
                            Picture = "erg"
                        },
                        new
                        {
                            T_ID = 2,
                            Name = "Magdalena Sikora",
                            Picture = "erg"
                        });
                });

            modelBuilder.Entity("HoE.CoreBusiness.SummaryTable", b =>
                {
                    b.HasOne("HoE.CoreBusiness.Kalendar", "Kalendar")
                        .WithMany("SummaryTable")
                        .HasForeignKey("K_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoE.CoreBusiness.Level", "Level")
                        .WithMany("SummaryTable")
                        .HasForeignKey("L_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoE.CoreBusiness.Student", "Student")
                        .WithMany("SummaryTable")
                        .HasForeignKey("S_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoE.CoreBusiness.TLevels", null)
                        .WithMany("SummaryTable")
                        .HasForeignKey("TLevelsT_ID");

                    b.HasOne("HoE.CoreBusiness.Teacher", "Teacher")
                        .WithMany("SummaryTable")
                        .HasForeignKey("T_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalendar");

                    b.Navigation("Level");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HoE.CoreBusiness.TAvaliable", b =>
                {
                    b.HasOne("HoE.CoreBusiness.Kalendar", "Kalendar")
                        .WithMany("TAvaliable")
                        .HasForeignKey("K_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoE.CoreBusiness.Teacher", "Teacher")
                        .WithMany("TAvaliable")
                        .HasForeignKey("T_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalendar");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Kalendar", b =>
                {
                    b.Navigation("SummaryTable");

                    b.Navigation("TAvaliable");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Level", b =>
                {
                    b.Navigation("SummaryTable");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Student", b =>
                {
                    b.Navigation("SummaryTable");
                });

            modelBuilder.Entity("HoE.CoreBusiness.TLevels", b =>
                {
                    b.Navigation("SummaryTable");
                });

            modelBuilder.Entity("HoE.CoreBusiness.Teacher", b =>
                {
                    b.Navigation("SummaryTable");

                    b.Navigation("TAvaliable");
                });
#pragma warning restore 612, 618
        }
    }
}
